---
    name: canada - fetch latest travel-advisories data
    on:
      schedule:
        - cron: "2 7 * * *"
      workflow_dispatch: # allows manual triggering
    
    jobs:
      scheduled:
        runs-on: ubuntu-latest
        steps:
          - name: Fetches repo
            uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'
          - name: Install dependencies
            run: |-
              python3 -m pip install --upgrade pip
              pip install -r code/requirements.txt
          - name: Parse Canada travel advisories
            run: python3 code/canada.py
          - name: Check for changes and commit
            run: |-
              git config user.name "Travel Advisories Bot for Canada"
              git config user.email "actions@users.noreply.github.com"
              git add -A *.json
              git add -A *.csv
              git add -A canada/*.md
              git add -A canada/*.json
              git add -A canada/last_run.txt
              
              if git diff --cached --quiet --exit-code; then
                echo "No changes to commit."
                exit 0
              fi
              
              if [[ $(git diff --cached --name-only) == "canada/last_run.txt" ]]; then
                echo "Only canada/last_run.txt has changed, skipping commit."
                exit 0
              fi
    
              timestamp=$(date -u -Is)
              git commit -m "canada: update travel advisories data"
              git push