---
    name: ireland - fetch latest travel-advisories data
    on:
      schedule:
        - cron: "1 5 * * *"
      workflow_dispatch: # allows manual triggering
    
    jobs:
      scheduled:
        runs-on: ubuntu-latest
        steps:
          - name: Fetches repo
            uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'
          - name: Install dependencies
            run: |-
              python3 -m pip install --upgrade pip
              pip install -r code/requirements.txt
          - name: Parse Ireland travel advisories
            run: python3 code/ireland.py
          - name: Add results to repo
            run: |-
                git config user.name "Travel Advisories Bot for Ireland"
                git config user.email "actions@users.noreply.github.com"
                git add -A *.json
                git add -A *.csv
                git add -A *.md
                git add ireland/last_run.txt #add last_run.txt to ensure it's tracked for changes
                git commit -m "ireland: update travel advisories data" || exit 0
                git push