---
    name: unitedstates - fetch latest travel-advisories data
    on:
      schedule:
        - cron: "3 9 * * *"
      workflow_dispatch:      # allows manual triggering
    
    jobs:
      scheduled:
        runs-on: ubuntu-latest
        steps:
          - name: Fetches repo
            uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'
          - name: Install dependencies
            run: |-
              python3 -m pip install --upgrade pip
              pip install -r code/requirements.txt
          - name: Parse United States travel advisories
            run: |-
              python3 code/unitedstates.py
          - name: Add results to repo
            run: |-
              git config user.name "Travel Advisories Bot for United States"
              git config user.email "actions@users.noreply.github.com"
              git add -A *.json
              git add -A *.csv
              git add -A unitedstates/*.md
              git add -A unitedstates/*.json
              git add -A unitedstates/last_run.txt
              
              if git diff --cached --quiet --exit-code; then
                echo "No changes to commit."
                exit 0
              fi
              
              if [[ $(git diff --cached --name-only) == "unitedstates/last_run.txt" ]]; then
                echo "Only unitedstates/last_run.txt has changed, skipping commit."
                exit 0
              fi
    
              timestamp=$(date -u -Is)
              git commit -m "unitedstates: update travel advisories data"
              git push
    