---
    name: unitedkingdom - fetch latest travel-advisories data
    on:
      schedule:
        - cron: "1 6 * * *"
      workflow_dispatch: # allows manual triggering
    
    jobs:
      scheduled:
        runs-on: ubuntu-latest
        steps:
          - name: Fetches repo
            uses: actions/checkout@v2
          - name: Set up Python
            uses: actions/setup-python@v2
            with:
              python-version: '3.x'
          - name: Install dependencies
            run: |-
              python3 -m pip install --upgrade pip
              pip install -r code/requirements.txt
          - name: Parse United Kingdom travel advisories
            run: python3 code/unitedkingdom.py
          - name: Check for changes and commit
            run: |-
              git config user.name "Travel Advisories Bot for United Kingdom"
              git config user.email "actions@users.noreply.github.com"
              git add -A *.json
              git add -A *.csv
              git add -A unitedkingdom/*.md
              git add -A unitedkingdom/*.json
                if [ -f unitedkingdom/last_run.txt ]; then
                  git add -A unitedkingdom/last_run.txt
                fi
              
              if git diff --cached --quiet --exit-code; then
                echo "No changes to commit."
                exit 0
              fi
              
              if [[ $(git diff --cached --name-only) == "unitedkingdom/last_run.txt" ]]; then
                echo "Only unitedkingdom/last_run.txt has changed, skipping commit."
                exit 0
              fi
    
              timestamp=$(date -u -Is)
              git commit -m "unitedkingdom: update travel advisories data"
              git push